version: '2'
services:
  yiqi-admin:
    image: yiqi/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  yiqi-api:
    image: yiqi/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev